######################################################################
# Automatically generated by qmake (2.01a) vie oct 29 13:25:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += treeitem.h treemodel.h \
    bluez/manager.h \
    bluez/adapter.h \
    bluez/device.h
SOURCES += main.cpp treeitem.cpp treemodel.cpp \
    bluez/manager.cpp \
    bluez/adapter.cpp \
    bluez/device.cpp
