######################################################################
# Automatically generated by qmake (2.01a) vie oct 29 13:25:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    bluez/manager.h \
    bluez/adapter.h \
    bluez/device.h \
    adapterview.h \
    mainwindow.h
SOURCES += main.cpp \
    bluez/manager.cpp \
    bluez/adapter.cpp \
    bluez/device.cpp \
    adapterview.cpp \
    mainwindow.cpp

FORMS += \
    adapterview.ui
